batch_size = 48
seq_len = 16000
rollouts_per_example = 4
max_steps = 150
mask_truncated_completions = false

[wandb]
project = "swe-grep-oss"

[model]
name = "willcb/Qwen3-4B"

[[env]]
id = "swe-grep-oss-env"

[ckpt]
interval = 10