batch_size = 48
seq_len = 20000
rollouts_per_example = 4
max_steps = 150
mask_truncated_completions = false

[wandb]
project = "swe-grep-oss"

[model]
name = "willcb/Qwen3-4B"

[[env]]
id = "swe-grep-oss-env"

[ckpt]
interval = 10

[val]
interval = 5
num_examples = 20
rollouts_per_example = 3