batch_size = 48
seq_len = 40000
rollouts_per_example = 16
max_steps = 50
mask_truncated_completions = false

[wandb]
project = "swe-grep-oss"

[model]
name = "willcb/Qwen3-8B"

[[env]]
id = "swe-grep-oss-env"

[ckpt]
interval = 10