batch_size = 24
seq_len = 16000
rollouts_per_example = 8
max_steps = 50
mask_truncated_completions = false

[wandb]
project = "swe-grep-oss"

[model]
name = "willcb/Qwen3-4B"

[[env]]
id = "swe-grep-oss-env"

[ckpt]
interval = 10
